name: Modules
options:
  bundleIdPrefix: com.XcodegenExample.mfd
  createIntermediateGroups: true
  generateEmptyDirectories: true
  deploymentTarget: 
    iOS: "13.0"
    tvOS: "13.0"
attributes: 
  ORGANIZATIONNAME: "mfd corp"
include: 
  - path: xcodegen/module-template.yml
    relativePaths: false
  - path: xcodegen/networking.yml
    relativePaths: false