name: Modules
options:
  bundleIdPrefix: com.XcodegenExample.mfd
  createIntermediateGroups: true
  generateEmptyDirectories: true
attributes: 
  ORGANIZATIONNAME: "mfd corp"
include: 
  - path: xcodegen/module-template.yml
    relativePaths: false
  - path: xcodegen/networking.yml
    relativePaths: false