name: Features
options:
  bundleIdPrefix: com.XcodegenExample.mfd
  createIntermediateGroups: true
  generateEmptyDirectories: true
attributes: 
  ORGANIZATIONNAME: "mfd corp"
include: 
  - path: xcodegen/feature-template.yml
    relativePaths: false
  - path: xcodegen/profiles.yml
    relativePaths: false