targets:
  ProfilesFeature:
    templates: 
      - feature
    templateAttributes:
      name: ProfilesFeature
  ProfilesFeatureTests:
    templates:
      - feature-unit-tests
    templateAttributes:
      name: ProfilesFeatureTests
