name: XcodeGenExample
options:
  bundleIdPrefix: com.xcodeGenExample.mfd
targets: 
  xcode-gen-ios: 
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: 
      path: XcodeGenExample
    dependencies: 
      - target: Networking
      - target: Caching
      - target: ProfilesFeature
    scheme: 
      testTarget:
        - xcode-gen-ios-unit-tests
        - xcode-gen-ios-ui-tests
    xcode-gen-ios-unit-tests:
      type: bundle.unit-tests
      platform: iOS
      sources: 
        - path: xcode-gen-unit-tests
    xcode-gen-ios-ui-tests:
      type: bundle.ui-testing
      platform: iOS
      sources: 
        - path: xcode-gen-ui-tests
  xcode-gen-tvos: 
    type: application
    platform: tvOS
    deploymentTarget: "13.0"
    sources: 
      path: XcodeGenExample
    dependencies: 
      - target: Networking
      - target: Caching
      - target: ProfilesFeature
    scheme: 
      testTarget:
        - xcode-gen-tvos-unit-tests
        - xcode-gen-tvos-ui-tests
    xcode-gen-tvos-unit-tests:
      type: bundle.unit-tests
      platform: tvOS
      sources: 
        - path: xcode-gen-unit-tests
    xcode-gen-tvos-ui-tests:
      type: bundle.ui-testing
      platform: tvOS
      sources: 
        - path: xcode-gen-ui-tests
include: 
  - modules.yml
  - path: modules/modules.yml
    relativePaths: false
  - features.yml
  - path: features/features.yml
    relativePaths: false